src/components/input/input.stories.tsx
src/components/input/input.tsx

This pull request is resolves #11

[#11] feat: input컴포넌트 제작

---

src/components/attendance/attendanceBoard.tsx
src/components/attendance/list/classList.tsx
src/components/dashboard/board/board.tsx
src/components/dashboard/card/attendanceCard.tsx
src/hooks/useLink.ts
src/utils/stackRouter.ts

react native route event 변경
- stack으로 쌓을 때 title 설정
- 새로운 팝업으로 열리는 경우 detail 페이지를 열어야해서 page props 추가

[#17] refactor: 라우트 이벤트 페이지, 제목 추가

---

src/app/dashboard/layout.tsx
src/app/error.tsx
src/app/loading.tsx
src/app/login/loading.tsx
src/app/login/page.tsx
src/lib/actions/auth.ts

This pull request resolves #25 
로그인 오류 수정
- 로그인 액션 수정
- 클라이언트 컴포넌트에서 서버 액션 호출하는 방식 변경

[#25] fix: 로그인 오류 수정

---

src/app/login/page.tsx

This pull request resolves #48 
- 로그인 페이지 UI

[#48] feat: 로그인 페이지 UI

---

src/utils/stackRouter.ts

This pull request resolves #54 
룰렛 페이지 라우터 오류 수정

[#54] fix: 룰렛 페이지 라우터 오류 수정

---

src/components/common/stackHeader/stackHeader.tsx

This pull request resloves #58 
- 스택 라우팅 헤더 스타일 수정

[#58] chore: 스택 라우팅 헤더 스타일 수정

---

src/app/(root)/dashboard/studyroom/studyRoomView.tsx
src/components/studyroom/list/studyRoomSlotList.tsx
src/lib/actions/studyroom.ts

closes #69 
- 스터디룸 필터 중 `시작시간 ~ 끝나는 시간` 쿼리 프론트에서 하도록 변경
- filterStudyRooms 함수 추가 후 필터링

[#69] feat: 스터디룸 시간 쿼리 프론트로 변경

---

src/components/dashboard/card/studyRoomCard.tsx
src/components/studyroom/list/studyRoomSlotItem.tsx

- 홈화면 스터디룸 라우팅 해제 및 디자인 (shrinking when touch) 해제
- 스터디룸 슬롯 primary 색상 변경

[#93] fix: 스터디룸 QA 이슈 해결 (디자인)

---

src/components/studyroom/list/studyRoomSlotItem.tsx
src/components/studyroom/list/studyRoomSlotList.tsx
src/components/studyroom/reservationForm.tsx

- 스터디룸 슬롯 리스트에서 토요일 -> endsAt 18시로 변경
- 스터디룸 reservation form에서 현재 시간 이전 슬롯 비활성화

[#85] fix: 스터디룸 토요일 개방 시간 18시로 변경

---

src/components/roulette/iconRoulette.tsx
src/components/roulette/menuRoulette.tsx

- 하단 룰렛 마지막 부분 following comma 존재하던 것 제거
- 메인화면 텍스트 움직이는 부분 돌돌돌로 변경

[#86] fix: 점메추 일부 QA 수정

---

src/app/login/page.tsx
src/app/stack/privacy/page.tsx

This pull request resolves #125 
---
- 인앱 개인정보 처리방침 추가

[#125] feat: 개인정보 처리방침 추가

---

src/app/login/page.tsx

This pull request resolves  #128 
---
로그인 페이지에서 세종대 타이틀 제거

[#128] remove: 세종대 타이틀 제거

---

src/app/stack/attendance/[id]/page.tsx

This pull request resolves #131 
---
출석 상세 페이지 스크롤 이슈 해결

[#131] fix: 출석 세부페이지 스크롤 이슈 해결

---

src/lib/actions/attendance.ts
src/lib/actions/discord.ts
src/lib/actions/studyroom.ts
src/utils/fetchExtended.ts

This pull request resolves #134 
---
핸들링 되지 않은 에러에 대하여 discrod 훅을 추가했습니다.
- 내 스터디룸 예약현황 조회,  출석업데이트의 경우 재요청에도 훅을 걸어두었습니다.

[#134] feat: api오류 디스코드 훅 추가

---

src/components/studyroom/list/studyRoomSlotItem.tsx
src/components/studyroom/list/studyRoomSlotList.tsx

온클릭이랑 transition 이펙트가 두쪽에 나눠져 있어서 일단은 ... 
원본유지로 나눠서 작성했습니다

[#179] fix: 스터디룸 슬롯 정보에 따라 온클릭 변경

---

src/app/global.css
src/components/classic/infoSelector.tsx
src/components/classic/stackContent.tsx
src/components/classic/timeSlotSelector.tsx
src/middleware.ts

고독 캘린더 슬롯 여러개 생기는 이슈 및 스타일 수정

---

src/app/stack/notion/page.tsx
src/auth.ts
src/components/classic/goteukReservationList.tsx
src/components/classic/timeSlotSelector.tsx
src/components/mypage/menuList.tsx
src/utils/fetchExtended.ts

- 마이페이지 - FAQ를 마이페이지 - 공지사항 으로 변경했습니다.

hotfix: 공지사항 추가

---

src/components/studyroom/list/studyRoomSlotItem.tsx
src/lib/definitions.ts

SL에 좌식, 콘센트 유무 정보들 보여주기 위해서 태그를 추가했습니다.

[#200] feat: 스터디룸 태그 추가

---

src/app/stack/portal/page.tsx
src/app/update/loading.tsx
src/app/update/page.tsx
src/components/common/portal-button.tsx
src/lib/actions/attendance.ts
src/utils/fetchExtended.ts

---
- 계정 잠겼을때 오류 처리
- 계정확인 portal iframe

[#203] fix: 계정 잠김시 에러 처리

---

src/app/stack/portal/page.tsx
src/app/update/loading.tsx
src/app/update/page.tsx
src/components/common/portal-button.tsx
src/lib/actions/attendance.ts
src/middleware.ts
src/utils/fetchExtended.ts

[BUG] 로그인 오류 페이지 

---

src/app/login/page.tsx
src/app/update/page.tsx

로그인시 pending상태 추가

---

src/app/(root)/dashboard/(overview)/layout.tsx
src/app/(root)/dashboard/(overview)/page.tsx
src/app/(root)/dashboard/layout.tsx
src/components/common/navLinks/NavLinks.tsx
src/components/studyroom/studyRoomBoard.tsx

[#221] 고전독서 임시 제거

---

src/app/(root)/dashboard/layout.tsx
src/components/notice/noticeModal.tsx
src/hooks/useModal.tsx
src/lib/actions/noticePopUp.ts

resolves #227 
localStorage, sessionStorage를  이용해서 모달 팝업 기능구현 완료하였습니다!

[#227, SEGAM-33] 공지사항 긴급 공지 팝업 로직

---

src/app/stack/notion/[id]/error.tsx
src/app/stack/notion/[id]/page.tsx
src/components/notion/noticeDetail.tsx
src/components/notion/noticeList.tsx
src/lib/actions/notice.ts

resolves #274 
공지사항 상세페이지 조회 ui와 로직 구현 완료했습니다.

[#274, SEGAM-82] 공지사항 조회 상세페이지 제작

---

src/app/(root)/dashboard/(overview)/page.tsx
src/app/(root)/dashboard/layout.tsx
src/components/common/noticeModal.tsx
src/components/notice/noticeModal.tsx
src/hooks/useModal.tsx
src/lib/actions/noticePopUp.ts
src/lib/definitions.ts

resolves #224 
모달 팝업 UI구현 완료하였습니다!
관련 로직은 새로운 branch에서 작업할 예정입니다.

[#224, SEGAM-27] 공지사항 긴급 공지 팝업 표시

---

src/app/(root)/admin/dashboard/[id]/edit/error.tsx
src/app/(root)/admin/dashboard/[id]/edit/page.tsx
src/app/(root)/admin/dashboard/[id]/view/page.tsx
src/app/(root)/admin/dashboard/create/page.tsx
src/app/(root)/admin/dashboard/page.tsx
src/components/admin/PopupButton.tsx
src/components/admin/adminNoticeForm.tsx
src/components/admin/adminTable.tsx
src/lib/actions/admin.ts
src/lib/actions/discord.ts
src/lib/definitions.ts

resolves #279 
어드민 페이지에서 공지사항 상세조회, 수정, 팝업 등록 기능 구현했습니다.

[#279, SEGAM-85] 어드민 공지사항 관리 기능 구현

---

src/app/(root)/admin/dashboard/[id]/view/page.tsx
src/lib/actions/admin.ts

[#281, SEGAM-86] 어드민 공지사항 상세조회 페이지 캐시 관련 오류 해결

---

src/components/notion/noticeDetail.tsx

[#284, SEGAM-87] hotfix: 공지사항 상세페이지 line-height 조정

---

src/components/studyroom/list/studyRoomSlotItem.tsx

- 스터디룸 예약현황 조회 시 운영시간 기준 -> 슬롯 데이터 기반으로 변경

[#286, SEGAM-92] 스터디룸 슬롯 리팩토링
